// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcqfkrM7CzyilcJdf0ckCqSg-cs-Qgoc',
    appId: '1:32644345180:web:dff16b47fe012b092a2599',
    messagingSenderId: '32644345180',
    projectId: 'sho-pinit',
    authDomain: 'sho-pinit.firebaseapp.com',
    storageBucket: 'sho-pinit.appspot.com',
    measurementId: 'G-WMY027B4K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9oJmxbQGIYPDQx1bUTT24ImQ2yagxd34',
    appId: '1:32644345180:android:2c7ac5fa3c5ff1542a2599',
    messagingSenderId: '32644345180',
    projectId: 'sho-pinit',
    storageBucket: 'sho-pinit.appspot.com',
  );
}
